@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.toast.apocalypse.common.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;